#ifndef FACEAR_DETECT_GLOBAL_H
#define FACEAR_DETECT_GLOBAL_H



#if defined(FACEAR_DETECT_LIBRARY)
#  define FACEAR_DETECTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FACEAR_DETECTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FACEAR_DETECT_GLOBAL_H
